WebSite/Areas/API/Controllers/MedicoController.cs
using AppServices.Dtos;
using AppServices.Filters;
using AppServices.Interfaces;
using System.Collections.Generic;
using System.Web.Http;

namespace WebSite.Areas.API.Controllers
{
    public class MedicoController : ApiController
    {
        private readonly IMedicoAppService _appService;

        public MedicoController(IMedicoAppService appService)
        {
            _appService = appService;
        }

        // GET: api/Medico
        public IEnumerable<MedicoDto> Get([FromBody]MedicoFilterDto filter)
        {
            return _appService.List(filter);
        }

        // GET: api/Medico/5
        public MedicoDto Get(int id)
        {
            return _appService.GetById(id);
        }

        // POST: api/Medico
        public MedicoDto Post([FromBody]MedicoDto value)
        {
            return _appService.Create(value);
        }

        // PUT: api/Medico/5
        public bool Put([FromBody]MedicoDto value)
        {
            return _appService.Update(value);
        }

        // DELETE: api/Medico/5
        public bool Delete(int id)
        {
            return _appService.Delete(id);
        }
    }
}

WebSite/Areas/Laudo/Controllers/MedicoController.cs
using AppServices.Dtos;
using AppServices.Filters;
using AppServices.Interfaces;
using PagedList;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebSite.Helper;

namespace WebSite.Areas.Laudo.Controllers
{
    public class MedicoController : Controller
    {
        private readonly IMedicoAppService _appService;

        // Constructor
        public MedicoController(IMedicoAppService appService)
        {
            _appService = appService;
        }

        // GET: Medico
        [HttpGet]
        [CustomAuthorize]
        public ActionResult Index(int? pageNumber)
        {
            IEnumerable<MedicoDto> model;
            try
            {
                // Tenta buscar os dados no banco utilizando um filtro vazio (busca todos os registros)
                MedicoFilterDto filter = new MedicoFilterDto();
                model = _appService.List(filter).ToPagedList(pageNumber ?? 1, Configuration.PageSize);
            }
            catch (Exception ex)
            {
                model = new List<MedicoDto>();
                // Adiciona uma mensagem de erro
                TempData["error"] = "Erro ao carregar a lista de médicos. " + ex.Message;
            }
            // retorna o model vazio com a mensagem de erro, ou o model com os dados
            return View(model);
        }

        // GET: Medico/Create
        [HttpGet]
        [CustomAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        // GET: Medico/Create
        [HttpPost]
        [CustomAuthorize]
        public ActionResult Create(MedicoDto model)
        {
            try
            {
                // se o model não estiver válido, retorna para view
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                model.MedicoDtCadastro = Util.HrBrasilia();
                // salva em banco
                _appService.Create(model);

                // add mensagem de sucesso e retorna para Index
                TempData["success"] = "Médico cadastrado com sucesso.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Adiciona uma mensagem de erro e mantem na mesma página
                TempData["error"] = "Erro ao cadastrar médico. " + ex.Message;
                return View(model);
            }
        }

        // POST: Medico/Create2
        [HttpPost]
        [CustomAuthorize]
        public JsonResult Create2(MedicoDto model)
        {
            MedicoDto m = null;
            try
            {
                model.MedicoDtCadastro = Util.HrBrasilia();
                // salva em banco
                m = _appService.Create(model);
                return Json(new { result = "ok", data = m }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { result = "error", data = "Erro: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Medico/Details/{id}
        [HttpGet]
        [CustomAuthorize]
        public ActionResult Details(int id)
        {
            try
            {
                MedicoDto model = _appService.GetById(id);
                return View(model);
            }
            catch (Exception ex)
            {
                // Adiciona uma mensagem de erro e retorna para Index
                TempData["error"] = "Erro ao carregar detalhes do médico. " + ex.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Medico/Edit/{id}
        [HttpGet]
        [CustomAuthorize]
        public ActionResult Edit(int id)
        {
            try
            {
                MedicoDto model = _appService.GetById(id);
                return View(model);
            }
            catch (Exception ex)
            {
                // Adiciona uma mensagem de erro e retorna para Index
                TempData["error"] = "Erro ao carregar detalhes do médico. " + ex.Message;
                return RedirectToAction("Index");
            }
        }

        // POST: Medico/Edit
        [HttpPost]
        [CustomAuthorize]
        public ActionResult Edit(MedicoDto model)
        {
            try
            {
                // se o model não estiver válido, retorna para view
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                // salva em banco
                bool editou = _appService.Update(model);

                if (editou)
                {
                    // add mensagem de sucesso e retorna para Index
                    TempData["success"] = "Médico editado com sucesso.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Erro ao editar médico.";
                }
            }
            catch (Exception ex)
            {
                // Adiciona uma mensagem de erro e mantem na mesma página
                TempData["error"] = "Erro ao editar médico. " + ex.Message;
            }
            return View(model);
        }

        // GET: Medico/Delete/{id}
        [HttpGet]
        [CustomAuthorize]
        public ActionResult Delete(int id)
        {
            try
            {
                // deleta do banco
                bool deletou = _appService.Delete(id);
                if (deletou)
                {
                    TempData["success"] = "Médico deletado com sucesso.";
                }
                else
                {
                    TempData["error"] = "Erro ao deletar médico.";
                }
            }
            catch (Exception ex)
            {
                // Adiciona uma mensagem de erro e retorna para Index
                TempData["error"] = "Erro ao deletar médico. " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        // Retorna uma lista de médicos filtrando pelo termo passado por parâmetro
        // É utilizado na chamada ajax
        [CustomAuthorize]
        public JsonResult GetMedicos(string term = "")
        {
            MedicoFilterDto filter = new MedicoFilterDto();
            if (!string.IsNullOrEmpty(term))
            {
                filter.MedicoNome = term;
            }
            IEnumerable<MedicoDto> medicos = _appService.List(filter);
            return Json(medicos, JsonRequestBehavior.AllowGet);
        }
    }
}

WebSite/Areas/Laudo/Views/Medico/Create.cshtml
<link rel="stylesheet" href="~/Content/main.css" />

@model AppServices.Dtos.MedicoDto

@{
    ViewBag.Title = "Novo";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <section id="create_medico" class="main special">
        <div class="container">
            <div class="content">
                <header class="major">
                    <h2>Novo Médico</h2>
                </header>
                <div class="row uniform">
                    <div class="6u 12u$(xsmall)">
                        @Html.EditorFor(model => model.MedicoNome, new { htmlAttributes = new { @placeholder = "Nome", @required = "required" } })
                    </div>
                    <div class="6u$ 12u$(xsmall)">
                        @Html.EditorFor(model => model.MedicoCRM, new { htmlAttributes = new { @placeholder = "CRM", @required = "required" } })
                    </div>
                    <div class="12u$">
                        <ul class="actions">
                            <li>@Html.ActionLink("Cancelar", "Index", "Medico", null, new { @class = "button special scrolly" })</li>
                            <li><input type="submit" value="Cadastrar" class="button special scrolly" /></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </section>
}

WebSite/Areas/Laudo/Views/Medico/Details.cshtml
<link rel="stylesheet" href="~/Content/main.css" />

<section id="details_medico" class="main">
    <div class="container">
        <div class="content">
            <header class="major">
                <h2>Médico</h2>
            </header>
            <section>
                <ul class="actions">
                    <li><a href="~/Laudo/Medico/Create" class="button special scrolly">Novo</a></li>
                </ul>
                <div class="table-wrapper">
                    <table>
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>CRM</th>
                                <th>Alterar</th>
                                <th>Excluir</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Daniele Alves</td>
                                <td>123456789</td>
                                <td>@Html.ActionLink("Alterar", "Edit")</td>
                                <td>@Html.ActionLink("Excluir", "Index")</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
    </div>
</section>

WebSite/Areas/Laudo/Views/Medico/Edit.cshtml
<link rel="stylesheet" href="~/Content/main.css" />

@model AppServices.Dtos.MedicoDto

@{
    ViewBag.Title = "Novo";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.MedicoId)
    <section id="create_medico" class="main special">
        <div class="container">
            <div class="content">
                <header class="major">
                    <h2>ALterar médico</h2>
                </header>
                <div class="row uniform">
                    <div class="6u 12u$(xsmall)">
                        @Html.EditorFor(model => model.MedicoNome, new { htmlAttributes = new { @placeholder = "Nome", @required = "required" } })
                    </div>
                    <div class="6u$ 12u$(xsmall)">
                        @Html.EditorFor(model => model.MedicoCRM, new { htmlAttributes = new { @placeholder = "CRM", @required = "required" } })
                    </div>
                    <div class="12u$">
                        <ul class="actions">
                            <li>@Html.ActionLink("Cancelar", "Index", "Medico", null, new { @class = "button special scrolly" })</li>
                            <li><input type="submit" value="Alterar" class="button special scrolly" /></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

WebSite/Areas/Laudo/Views/Medico/Index.cshtml
<link rel="stylesheet" href="~/Content/main.css" />

@using PagedList.Mvc
@model PagedList.IPagedList<AppServices.Dtos.MedicoDto>

@{
    ViewBag.Title = "Index";
}

<section id="details_medico" class="main">
    <div class="container">
        <div class="content">
            <header class="major">
                <h2>Médico</h2>
            </header>
            <section>
                <ul class="actions">
                    <li>@Html.ActionLink("Novo", "Create", null, new { @class = "button special scrolly" })</li>
                </ul>
                <div class="table-wrapper">
                    <table>
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>CRM</th>
                                <th>Alterar</th>
                                <th>Excluir</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.MedicoNome)</td>
                                    <td>@Html.DisplayFor(modelItem => item.MedicoCRM)</td>
                                    <td>@Html.ActionLink("Alterar", "Edit", new { id = item.MedicoId })</td>
                                    <td>@Html.ActionLink("Excluir", "Delete", new { id = item.MedicoId })</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                @Html.PagedListPager(Model, pageNumber => Url.Action("Index", new { pageNumber }))
            </section>
        </div>
    </div>
</section>